### ISSUE TITLE
Matlab for AWS Batch

### ISSUE THREAD

**Issue by chadbrewbaker** [jfluet/helloworld#2]
I have a project that needs Matlab running on EC2 under AWS Batch for image processing.

For the life of me I can't figure out how to get the advertised on demand pricing or the Matlab Linux image. Preferably something compatible with Ubuntu 18.04 or AWSLinux.

My alternative is exporting it to C code and not give Mathworks any revenue for the SAAS.

**Comment by jfluet** [comment]
Your best bet would be to contact [MathWorks support](https://www.mathworks.com/support.html) directly.  They can help you through the pricing and licensing issues.
